### ISSUE TITLE
Shareable dotfiles via npm package for prettier and eslint

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/kwiz-dotfiles#1]
### Description

In order to now have to maintain config files across all our repositories, it would be nice to have them published in a package that can be extended inside `eslintrc` and `prettierrc`.

### Tasks

- [x] create new repositories containing the commom configuration files
- [x] for eslint make sure to include default and one for react projects
- [x] decide on a common prettier code style
- [x] add workflow to create and publish npm package on GPR

### Context 
https://github.com/kwizapp/metadata-service/issues/7
https://github.com/kwizapp/poster-service/issues/17
