### ISSUE TITLE
Publish separate packages for eslint and prettier configs

### ISSUE THREAD

**Issue by nikzaugg** [kwizapp/kwiz-dotfiles#3]
### Description

Right now, this repository published one package `kwizapp/eslint-config` which holds both configuration files for prettier and eslint. 

### Tasks
To make this more manageable, the optimal setup would be the following:
- [x] rename this repository into `kwiz-dotfiles`
- [x] within `kwiz-dotfiles` there are the following two folders
  - [x] `eslint-configs/**`
  - [x] `prettier-config/`
- [x] each of these subfolders have their own `package.json` and publish different packages
- [x] `eslint/` publishes `@kwizapp/eslint-config/**`
- [x] `prettier/` published `@kwizapp/prettier-config`
- [x] add READMEs
- [x] `dependencies` inside `package.json` based on ranges
- [x] update workflow to not publish new package with each push
